version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: memo-db
    restart: always
    environment:
      MYSQL_DATABASE: memo_db
      MYSQL_ROOT_PASSWORD: 3535
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: my-memo-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./memo_files:/memo_files
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/memo_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 3535
