# DB 연결 주소 및 계정 정보
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/memo_db?serverTimezone=Asia/Seoul
spring.datasource.username=root

# MySQL 비밀번호
spring.datasource.password=3535

# JPA 설정(자바 코드로 DB 테이블을 자동으로 만들어 줌)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 로그인 아이디 비밀번호
spring.security.user.name=minjun
spring.security.user.password=3535